/* eslint-disable no-restricted-imports */
import { mutation as rawMutation, internalMutation as rawInternalMutation, query as rawQuery, internalQuery as rawInternalQuery } from "./_generated/server";
/* eslint-enable no-restricted-imports */
import { customCtx, customMutation, customQuery } from "convex-helpers/server/customFunctions";
import { entsTableFactory } from "convex-ents";
import { entDefinitions } from "./schema";
import { Triggers } from "convex-helpers/server/triggers";
// import { components } from "./components"; // generated by the CLI
import { components } from "./_generated/api";
import { TableAggregate } from "@convex-dev/aggregate";
import type { DataModel, Id, Doc } from "./_generated/dataModel";

const triggers = new Triggers<DataModel>();
const timeEntriesByUser = new TableAggregate<{
  Namespace: Id<"users">;
  Key: null;
  DataModel: DataModel;
  TableName: "time_entries";
}>(components.aggregate, {
  namespace: (d) => d.userId,
  // We only need counts, so a constant key is fine
  sortKey: () => null,
});

// keep ents for ctx.table
// (no standalone helper; we inline it below to satisfy linter)

// Keep the aggregate in sync with table writes
triggers.register("time_entries", async (ctx, change) => {
  if (change.operation === "insert") {
    await timeEntriesByUser.insert(ctx, change.newDoc as Doc<"time_entries">);
  } else if (change.operation === "update") {
    try {
      await timeEntriesByUser.replace(
        ctx,
        change.oldDoc as Doc<"time_entries">,
        change.newDoc as Doc<"time_entries">
      );
    } catch (err) {
      // If the previous aggregate key was never inserted (e.g., docs existed before triggers),
      // fall back to inserting the new doc into the aggregate to self-heal.
      await timeEntriesByUser.insert(ctx, change.newDoc as Doc<"time_entries">);
    }
  } else if (change.operation === "delete") {
    try {
      await timeEntriesByUser.delete(ctx, change.oldDoc as Doc<"time_entries">);
    } catch (err) {
      // Ignore missing-key deletes: aggregate may not have contained this doc.
    }
  }
});

export const query = customQuery(rawQuery, customCtx(async (ctx) => {
  return { table: entsTableFactory(ctx, entDefinitions) };
}));
export const internalQuery = customQuery(rawInternalQuery, customCtx(async (ctx) => {
  return { table: entsTableFactory(ctx, entDefinitions) };
}));
// compose triggers + ents for mutations; wrap db then add ents table
export const mutation = customMutation(
  rawMutation,
  customCtx(async (ctx) => {
    const wrapped = triggers.wrapDB(ctx);
    return { db: wrapped.db, table: entsTableFactory(wrapped, entDefinitions) };
  })
);
export const internalMutation = customMutation(
  rawInternalMutation,
  customCtx(async (ctx) => {
    const wrapped = triggers.wrapDB(ctx);
    return { db: wrapped.db, table: entsTableFactory(wrapped, entDefinitions) };
  })
);