/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appProjectsRouteImport } from './routes/(app)/projects'
import { Route as appClientsRouteImport } from './routes/(app)/clients'
import { Route as appCategoriesRouteImport } from './routes/(app)/categories'
import { Route as appAnalyticsRouteImport } from './routes/(app)/analytics'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appProjectsRoute = appProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => appRouteRoute,
} as any)
const appClientsRoute = appClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesRoute = appCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/analytics': typeof appAnalyticsRoute
  '/categories': typeof appCategoriesRoute
  '/clients': typeof appClientsRoute
  '/projects': typeof appProjectsRoute
  '/settings': typeof appSettingsRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof appAnalyticsRoute
  '/categories': typeof appCategoriesRoute
  '/clients': typeof appClientsRoute
  '/projects': typeof appProjectsRoute
  '/settings': typeof appSettingsRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/categories': typeof appCategoriesRoute
  '/(app)/clients': typeof appClientsRoute
  '/(app)/projects': typeof appProjectsRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/': typeof appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/categories'
    | '/clients'
    | '/projects'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/categories'
    | '/clients'
    | '/projects'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/analytics'
    | '/(app)/categories'
    | '/(app)/clients'
    | '/(app)/projects'
    | '/(app)/settings'
    | '/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/projects': {
      id: '/(app)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof appProjectsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/clients': {
      id: '/(app)/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof appClientsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAnalyticsRoute: typeof appAnalyticsRoute
  appCategoriesRoute: typeof appCategoriesRoute
  appClientsRoute: typeof appClientsRoute
  appProjectsRoute: typeof appProjectsRoute
  appSettingsRoute: typeof appSettingsRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAnalyticsRoute: appAnalyticsRoute,
  appCategoriesRoute: appCategoriesRoute,
  appClientsRoute: appClientsRoute,
  appProjectsRoute: appProjectsRoute,
  appSettingsRoute: appSettingsRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
